tunnel: a0b83939-c4eb-47ca-857f-3c142b3a0ca9
credentials-file: C:\Users\User\.cloudflared\a0b83939-c4eb-47ca-857f-3c142b3a0ca9.json

ingress:
  - hostname: getkunlun.me
    path: /api/*
    service: http://localhost:3001
  - hostname: getkunlun.me
    service: https://32090-gif.github.io
  - service: http_status:404